export {default as Login} from './Login/Login'
export { default as Register } from './Register/Register'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
export { default as NewPassword } from './NewPassword/NewPassword'
export { default as Profile } from './Profile/Profile'